version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '91:83:d2:3f:f5:ba:1b:10:2d:83:f6:3b:a3:4e:83:38'
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan 178.128.10.75 >> ~/.ssh/known_hosts
      - run:
          name: The First Step
          command: |
            ls -a
            scp * -r circleci@178.128.10.75:/var/www/html
workflows:
  ex:
    jobs:
     # - cypress/run:
     #     yarn: true
      - deploy
     #     requires:
     #       - cypress/run