version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'ea:39:f9:18:8e:d8:79:1d:b7:bf:69:36:6b:b5:95:47'
      - run:
          name: The First Step
          command: |
            scp * -r root@178.128.10.75:/var/www/html
workflows:
  ex:
    jobs:
     # - cypress/run:
     #     yarn: true
      - deploy
     #     requires:
     #       - cypress/run