version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  deploy:
    machine:
      - enabled: true
    steps:
      - checkout
      - add_ssh_keys:
        fingersprints:
          - 'ea:39:f9:18:8e:d8:79:1d:b7:bf:69:36:6b:b5:95:47'
      - run:
          name: SSH Deployment to DigitalOcean
          command: |
            echo 'Hello World!'
workflows:
  ex:
    jobs:
      - cypress/run:
          yarn: true
      - deploy